"""anotha one

Revision ID: 0813e77d908d
Revises: e2d19936c984
Create Date: 2021-02-05 17:52:11.608327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0813e77d908d'
down_revision = 'e2d19936c984'
branch_labels = None
depends_on = None


def upgrade():
   # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'descri', new_column_name='descr')
    # ### end Alembic commands ###
    
    

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('descri', sa.VARCHAR(length=140), nullable=True))
    op.drop_column('project', 'descr')
    # ### end Alembic commands ###
