"""chat link

Revision ID: 4c47d9a4daa0
Revises: 5c579b267c11
Create Date: 2021-04-14 13:20:33.794543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c47d9a4daa0'
down_revision = '5c579b267c11'
branch_labels = None
depends_on = None


def upgrade():
   # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('chat_link', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###
    
    

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'chat_link')
    # ### end Alembic commands ###
