"""polymorph

Revision ID: 4f7bdcc08540
Revises: abc03a1715dd
Create Date: 2021-03-14 18:24:37.907676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f7bdcc08540'
down_revision = 'abc03a1715dd'
branch_labels = None
depends_on = None


def upgrade():
   # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(None, 'learning', type_='foreignkey')
    #op.create_foreign_key(None, 'learning', 'project', ['id'], ['id'])
    with op.batch_alter_table("learning") as batch_op:
        batch_op.drop_column('project_id')
    
    # ### end Alembic commands ###
    
    

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning', sa.Column('project_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'learning', type_='foreignkey')
    op.create_foreign_key(None, 'learning', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###
