"""resource for Learning

Revision ID: 5c579b267c11
Revises: ebac5871f3fb
Create Date: 2021-04-05 20:32:39.014054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c579b267c11'
down_revision = 'ebac5871f3fb'
branch_labels = None
depends_on = None


def upgrade():
   # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning', sa.Column('resource', sa.String(length=70), nullable=True))
    # ### end Alembic commands ###
    
    

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learning', 'resource')
    # ### end Alembic commands ###
