"""tags

Revision ID: 6ca5a034b67e
Revises: 4c47d9a4daa0
Create Date: 2021-04-14 17:58:00.614247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ca5a034b67e'
down_revision = '4c47d9a4daa0'
branch_labels = None
depends_on = None


def upgrade():
   # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag_map',
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    # ### end Alembic commands ###
    
    

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag_map')
    op.drop_table('tag')
    # ### end Alembic commands ###
