"""wanted positions

Revision ID: 92c844fbac6b
Revises: 6ca5a034b67e
Create Date: 2021-04-15 18:50:11.146659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92c844fbac6b'
down_revision = '6ca5a034b67e'
branch_labels = None
depends_on = None


def upgrade():
   # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('position_map',
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['position.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], )
    )

    # ### end Alembic commands ###
    
    

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('position_map')
    op.drop_table('position')
    # ### end Alembic commands ###
