"""project changs and Learning

Revision ID: abc03a1715dd
Revises: a252fc774bbd
Create Date: 2021-03-08 20:10:58.700973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abc03a1715dd'
down_revision = 'a252fc774bbd'
branch_labels = None
depends_on = None


def upgrade():
   # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pace', sa.String(length=60), nullable=True),
    sa.Column('learning_category', sa.String(length=60), nullable=True),
    sa.Column('subject', sa.String(length=60), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('project', sa.Column('setting', sa.String(length=20), nullable=True))
    op.add_column('project', sa.Column('skill_level', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###
    
    

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'skill_level')
    op.drop_column('project', 'setting')
    op.drop_table('learning')
    # ### end Alembic commands ###
