"""last_seen

Revision ID: b37a9f40c8c6
Revises: 4f7bdcc08540
Create Date: 2021-03-28 11:39:39.098951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b37a9f40c8c6'
down_revision = '4f7bdcc08540'
branch_labels = None
depends_on = None


def upgrade():
   # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###
    
    

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_constraint(None, 'learning', type_='foreignkey')
    # ### end Alembic commands ###
