"""new Project connstructors

Revision ID: c8adfc590fb8
Revises: 2375c9bbdf01
Create Date: 2021-01-29 19:51:56.249363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8adfc590fb8'
down_revision = '2375c9bbdf01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('descr', sa.String(length=140), nullable=True))
    op.add_column('project', sa.Column('name', sa.String(length=60), nullable=True))
    op.drop_column('project', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('description', sa.VARCHAR(length=140), nullable=True))
    op.drop_column('project', 'name')
    op.drop_column('project', 'descr')
    # ### end Alembic commands ###
