"""request assoc table

Revision ID: e19ad4bc00ef
Revises: 92c844fbac6b
Create Date: 2021-04-17 17:12:37.784795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e19ad4bc00ef'
down_revision = '92c844fbac6b'
branch_labels = None
depends_on = None


def upgrade():
   # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('join_requests',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=15), nullable=True),
    sa.Column('msg', sa.String(length=650), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'project_id')
    )
    op.create_index(op.f('ix_join_requests_timestamp'), 'join_requests', ['timestamp'], unique=False)

    # ### end Alembic commands ###
    
    

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_join_requests_timestamp'), table_name='join_requests')
    op.drop_table('join_requests')
    # ### end Alembic commands ###
