"""trying new col name

Revision ID: e2d19936c984
Revises: c8adfc590fb8
Create Date: 2021-02-05 17:44:52.946018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2d19936c984'
down_revision = 'c8adfc590fb8'
branch_labels = None
depends_on = None


def upgrade():
   # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'descri', new_column_name='descr')
    # ### end Alembic commands ###
    
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('descr', sa.VARCHAR(length=140), nullable=True))
    op.drop_column('project', 'descri')
    # ### end Alembic commands ###
