"""add language to projects

Revision ID: ebac5871f3fb
Revises: b37a9f40c8c6
Create Date: 2021-03-29 13:59:36.692940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebac5871f3fb'
down_revision = 'b37a9f40c8c6'
branch_labels = None
depends_on = None


def upgrade():
   # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###
    
    

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'language')
    op.drop_constraint(None, 'learning', type_='foreignkey')
    # ### end Alembic commands ###
