"""empty message

Revision ID: 1d3285457388
Revises: 0dc374fee000
Create Date: 2021-09-01 12:00:05.777542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d3285457388'
down_revision = '0dc374fee000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_creator_map',
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_column('project', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'project', 'user', ['user_id'], ['id'])
    op.drop_table('project_creator_map')
    # ### end Alembic commands ###
