"""empty message

Revision ID: 3217af0f3a71
Revises: 51b8a904f5d2
Create Date: 2021-08-02 19:05:39.034236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3217af0f3a71'
down_revision = '51b8a904f5d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_tag_map',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.rename_table('tag_map', 'project_tag_map')
  
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_map',
    sa.Column('project_id', sa.INTEGER(), nullable=True),
    sa.Column('tag_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    op.drop_table('project_tag_map')
    op.drop_table('user_tag_map')
    # ### end Alembic commands ###
