"""empty message

Revision ID: 4c9658123500
Revises: 3217af0f3a71
Create Date: 2021-08-13 16:49:35.881049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c9658123500'
down_revision = '3217af0f3a71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sub_category', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_science',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sub_category', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engineering',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sub_category', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entertainment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sub_category', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('software_dev',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sub_category', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('project', sa.Column('team_size', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'team_size')
    op.drop_table('software_dev')
    op.drop_table('research')
    op.drop_table('entertainment')
    op.drop_table('engineering')
    op.drop_table('data_science')
    op.drop_table('community')
    # ### end Alembic commands ###
