"""empty message

Revision ID: 5190d5ed0c88
Revises: 4c9658123500
Create Date: 2021-08-25 20:11:26.142808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5190d5ed0c88'
down_revision = '4c9658123500'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('descr', sa.String(length=140), nullable=True),
    sa.Column('link', sa.String(length=512), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_timestamp'), 'resource', ['timestamp'], unique=False)
    op.create_table('resource_tag_map',
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_tag_map')
    op.drop_index(op.f('ix_resource_timestamp'), table_name='resource')
    op.drop_table('resource')
    # ### end Alembic commands ###
