"""last read

Revision ID: bb94115505ee
Revises: fcb1e1c1dbef
Create Date: 2021-04-21 17:45:55.485510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb94115505ee'
down_revision = 'fcb1e1c1dbef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_notif_read_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_notif_read_time')
    # ### end Alembic commands ###
