"""scrum

Revision ID: e1b48319e9a7
Revises: bb94115505ee
Create Date: 2021-06-03 11:51:45.642737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1b48319e9a7'
down_revision = 'bb94115505ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrum_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('task_type', sa.String(length=15), nullable=True),
    sa.Column('text', sa.String(length=650), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrum_tasks_timestamp'), 'scrum_tasks', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scrum_tasks_timestamp'), table_name='scrum_tasks')
    op.drop_table('scrum_tasks')
    # ### end Alembic commands ###
